const express = require("express");
const { getAllPosts } = require("../controllers/Post_controller/getAllPosts");
const { UploadPost } = require("../controllers/Post_controller/UploadPost");
const { getPostById } = require("../controllers/Post_controller/getpostbyId");
const { getAllPostsByUser } = require("../controllers/Post_controller/getallpostsbyUser");
const { getAllPostsbyOtherUsers } = require("../controllers/Post_controller/getAllPostsbyOtherUsers");
const { ViewPost } = require("../controllers/Post_controller/ViewPost");
const { likePost } = require("../controllers/Post_controller/LikePost");
const router  = express.Router();
router.route("/allposts").get(getAllPosts);
router.route("/upload").post(UploadPost);
router.route("/getpostbyid").get(getPostById);
router.route("/getallpostsbyuser").get(getAllPostsByUser);
router.route("/getallpostsbyotheruser").get(getAllPostsbyOtherUsers);
router.route("/viewpost").get(ViewPost);
router.route("/like").post(likePost);
module.exports = router;